<li class="others">
                <div class="image">
                    <a href="[field:arcurl/]" title="[field:fulltitle/]">
                        <img src="[field:litpic function=firstimg('@me')/]" alt="[field:fulltitle/]" class="thumbnail" /></a>
                </div>
                <div class="title">
                    <h4><a href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a></h4>
                    <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                </div>
            </li>