<li>
                                <div class="item">
                                    <a href="[field:arcurl /]" title="[field:fulltitle /]">
                                        <div class="overlay"></div>
                                        <img class="thumbnail" src="[field:litpic function=firstimg('@me')/]" alt="[field:fulltitle /]">
                                        <h4><span>[field:title /]</span></h4>
                                    </a>
                                </div>
                            </li>