<div class="hots-item">
                                <a href="[field:arcurl/]">
                                    <div class="hots-image" style="background-image:url([field:litpic function=firstimg('@me')/])"></div>
                                    <h3>
                                        <i class="icon-record-outline"></i>
                                        <span>[field:title/]</span>
                                    </h3>
                                </a>
                            </div>