<div class="fistnew">
                        <center>
                            <a href="/news/1307.html" target="_blank">今日头条2019新年盛典,遇见奶牛总部荣获双料奖！</a>
                        </center>
                        <a href="/news/1307.html" target="_blank">
                            <img src="/uploadfile/2019/0114/20190114095103995.jpg" alt="今日头条2019新年盛典,遇见奶牛总部荣获双料奖！" width="195" height="120">
                        </a>
                        <a href="/news/1307.html" target="_blank">
                            <p>遇见奶牛总部杭州奇异鸟公司今日应邀参加今日头条新年盛典，并摘得“2018年度浙江热力传播奖”和“2018年度城市创新营销品牌奖”两项奖项。...</p>
                        </a>
                    </div>