
<field:lxmz itemname="您的名字" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxmz>

<field:lxdh itemname="您的电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxdh>

<field:lxqq itemname="您的QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxqq>

<field:lxly itemname="您的留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:lxly>
