<li class="one">
                <a href="/6679/lian_fengdingbin_/7.html" title="6大世界上至今无解的自然怪象">
                    <div class="overlay"></div>
                    <img class="thumbnail" src="/6679/uploads/allimg/20190220/066dbcb70a5c9c089fef7688a43446c6.jpg" alt="6大世界上至今无解的自然怪象" />
                    <div class="title">
                        <span>2019-02-20</span>
                        <h4>6大世界上至今无解的自然怪象</h4></div>
                </a>
            </li>