<li>
                    <span>[field:pubdate function='strftime("%y-%m",@me)'/]<br><strong>[field:pubdate function='strftime("%d",@me)'/]</strong></span>
                    <div>
                        <a href="[field:arcurl/]" target="_blank"><h4>[field:title /]</h4></a>
                        <p>[field:description function="cn_substr(@me,220)"/]...</p>
                    </div>
                    <a href="[field:arcurl/]"><img width="272" height="205" src="[field:litpic /]" alt="[field:fulltitle /]" /></a>
                </li>