<?php
$z[0]=Array("id","",300,337);
$z[0][4]=array();
$z[0][4]['function']="GetMyTags(@me,5)";
$z[1]=Array("arcurl","",474,490);
$z[1][4]=array();
$z[2]=Array("fulltitle","",499,518);
$z[2][4]=array();
$z[3]=Array("title","",520,535);
$z[3][4]=array();
$z[4]=Array("arcurl","",720,736);
$z[4][4]=array();
$z[5]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"123\" : \"<span class='thumb-span'><img src='{@me['litpic']}' class='thumb'></span>\"); ",863,1033);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<i><a href='{@me['arcurl']}'><img src='{@me['litpic']}' alt='{@me['title']}'></a></i>\"); ",1086,1265);
$z[6][4]=array();
$z[6][4]['runphp']="yes";
$z[7]=Array("description","",1531,1581);
$z[7][4]=array();
$z[7][4]['function']="cn_substr(@me,300)";
$z[8]=Array("writer","",1938,1954);
$z[8][4]=array();
$z[9]=Array("typename","",2237,2255);
$z[9][4]=array();
$z[10]=Array("pubdate","",2405,2452);
$z[10][4]=array();
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("click","",2550,2565);
$z[11][4]=array();

?>