<li>
                    <img src="[field:litpic /]" width="356" height="220" alt="[field:fulltitle /]">
                    <div>
                        <h3>[field:title /]</h3>
                        <span>点击量：[field:click /]</span>
                    </div>
                    <a href="[field:arcurl /]" target="_blank">
                        <img src="/skin/images/bf.png" width="60" height="60" /></a>
                </li>