<?php
$z[0]=Array("arcurl","",43,58);
$z[0][4]=array();
$z[1]=Array("fulltitle","",67,85);
$z[1][4]=array();
$z[2]=Array("litpic","",186,226);
$z[2][4]=array();
$z[2][4]['function']="firstimg('@me')";
$z[3]=Array("fulltitle","",233,251);
$z[3][4]=array();
$z[4]=Array("pubdate","",328,375);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("title","",412,426);
$z[5][4]=array();

?>