<li>
                    <span>[field:pubdate function='strftime("%Y-%m",@me)'/]<br><strong>[field:pubdate function='strftime("%d",@me)'/]</strong></span>
                    <div>
                        <a href="http://www.yujiannainiu.com/news/1470.html" target="_blank"><h4>现在经营奶茶加盟品牌店需要多少钱</h4></a>
                        <p>现在经营奶茶店需要多少钱？遇见奶牛奶茶店有创业店、标准店、旗舰店等类型，加盟遇见奶牛降低创业风险，减少投资成本。...</p>
                    </div>
                    <a href="http://www.yujiannainiu.com/news/1470.html"><img width="272" height="205" src="http://www.yujiannainiu.com/uploadfile/2019/0313/20190313090557255.jpg" alt="现在经营奶茶加盟品牌店需要多少钱" /></a>
                </li>