<?php
$z[0]=Array("pubdate","",32,81);
$z[0][4]=array();
$z[0][4]['function']="strftime(\"%y-%m\",@me)";
$z[1]=Array("pubdate","",93,139);
$z[1][4]=array();
$z[1][4]['function']="strftime(\"%d\",@me)";
$z[2]=Array("id","",230,241);
$z[2][4]=array();
$z[3]=Array("title","",247,261);
$z[3][4]=array();
$z[4]=Array("description","",299,349);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,300)";

?>