<?php
$z[0]=Array("arcurl","",31,46);
$z[0][4]=array();
$z[1]=Array("fulltitle","",55,73);
$z[1][4]=array();
$z[2]=Array("litpic","",174,214);
$z[2][4]=array();
$z[2][4]['function']="firstimg('@me')";
$z[3]=Array("fulltitle","",221,239);
$z[3][4]=array();
$z[4]=Array("pubdate","",370,417);
$z[4][4]=array();
$z[4][4]['function']="MyDate('Y-m-d',@me)";
$z[5]=Array("title","",486,500);
$z[5][4]=array();

?>