<li>
                <a href="[field:arcurl/]" title="[field:fulltitle/]">
                    <div class="overlay"></div>
                    <img class="thumbnail" src="[field:litpic function=firstimg('@me')/]" alt="[field:fulltitle/]" />
                    <div class="title">
                        <div class="entry-meta">
                            <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
                        </div>
                        <h4>[field:title/]</h4>
                    </div>
                </a>
            </li>