<?php
$z[0]=Array("id","",300,337);
$z[0][4]=array();
$z[0][4]['function']="GetMyTags(@me,5)";
$z[1]=Array("arcurl","",474,490);
$z[1][4]=array();
$z[2]=Array("fulltitle","",499,518);
$z[2][4]=array();
$z[3]=Array("title","",520,535);
$z[3][4]=array();
$z[4]=Array("arcurl","",720,736);
$z[4][4]=array();
$z[5]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<span class='item'><span class='thumb-span'><img src='{@me['litpic']}' class='thumb'></span></span>\"); ",804,997);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[6]=Array("array","@me = (strpos(@me['litpic'],'defaultpic') ? \"\" : \"<i><a href='{@me['arcurl']}'><img src='{@me['litpic']}' alt='{@me['title']}'></a></i>\"); ",1050,1229);
$z[6][4]=array();
$z[6][4]['runphp']="yes";
$z[7]=Array("description","",1448,1498);
$z[7][4]=array();
$z[7][4]['function']="cn_substr(@me,300)";
$z[8]=Array("writer","",1855,1871);
$z[8][4]=array();
$z[9]=Array("typename","",2154,2172);
$z[9][4]=array();
$z[10]=Array("pubdate","",2322,2369);
$z[10][4]=array();
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("click","",2467,2482);
$z[11][4]=array();

?>