</div>
            </div>
        </div>
    </div>
    <div class="yj index-store">
        <div class="yj1200">
            <div class="index-store-bt">
                <img src="/skin/images/logo-wz.png" width="135" height="60" />
                <img src="/skin/images/index-xxzs.png" width="140" height="60" />
                <img src="/skin/images/store.png" width="800" height="60" style="margin-left:20px;" />
                <div class="index-more">
                    <a href="/xingxiang/shop" target="_blank" rel="nofollow"><em>查看</em>更多></a>
                </div>
            </div>
        </div>
        <div class="yj">
            <div id="marquee4" class="marqueeleft">
                <div style="width:8000px;">
                    <ul id="marquee4_1">
                        {dede:arclist typeid='12' titlelen='45' row='8'}
                        <li>
                            <div><p>[field:title /]</p></div>
                            <span><a href="[field:arcurl/]" target="_blank" rel="nofollow">查看详情</a></span>
                            <img src="[field:litpic/]" alt="[field:fulltitle /]" width="300" height="220" />
                        </li>
                        {/dede:arclist}
                    </ul>
                    <ul id="marquee4_2"></ul>
                </div>
                <script type="text/javascript">marqueeStart(4, "left");</script></div>
        </div>
    </div><!-- //底部模板 -->
    {dede:include filename="foot.htm"