<div class="image">
                                <div class="index-cat-box" style="background-image:url([field:litpic function=firstimg('@me')/])">
                                    <a class="istop" href="[field:arcurl/]">
                                        <div class="overlay"></div>
                                        <div class="title">
                                            <span>[field:typename/]</span>
                                            <h3>[field:title/]</h3>
                                        </div>
                                    </a>
                                </div>
                            </div>