<?php
$z[0]=Array("arcurl","",94,109);
$z[0][4]=array();
$z[1]=Array("title","",127,142);
$z[1][4]=array();
$z[2]=Array("arcurl","",216,231);
$z[2][4]=array();
$z[3]=Array("litpic","",289,304);
$z[3][4]=array();
$z[4]=Array("fulltitle","",311,330);
$z[4][4]=array();
$z[5]=Array("arcurl","",422,437);
$z[5][4]=array();
$z[6]=Array("description","",488,538);
$z[6][4]=array();
$z[6][4]['function']="cn_substr(@me,200)";

?>