<div class="item" style="background: url([field:litpic function=firstimg('@me')/]); background-repeat: no-repeat;background-size: cover;background-position: center top;">
                            <div class="slider-content">
                                <div class="slider-content-item">
                                    <div class="slider-cat clearfix">[field:typename/]</div>
                                    <h2><a class="read-slider" href="[field:arcurl/]" title="[field:fulltitle/]">[field:title/]</a></h2>
                                </div>
                            </div>
                        </div>