<div class="fistnew">
                        <center>
                            <a href="[field:arcurl/]" target="_blank">[field:title /]</a>
                        </center>
                        <a href="[field:arcurl/]" target="_blank">
                            <img src="[field:litpic/]" alt="[field:fulltitle /]" width="195" height="120">
                        </a>
                        <a href="[field:arcurl/]" target="_blank">
                            <p>[field:description function="cn_substr(@me,300)"/]...</p>
                        </a>
                    </div>