<?php
$z[0]=Array("channel","\r\n                <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n                ",1133,1257);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[1]=Array("global","",1342,1368);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",1447,1471);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("flink","[field:link /]",1603,1677);
$z[3][4]=array();
$z[3][4]['row']="30";
$z[3][4]['type']="text";
$z[3][4]['titlelen']="26";

?>