<?php
$z[0]=Array("channelartlist","\r\n            <li>\r\n                <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n                <div class=\"Nodes\">\r\n                    <ul>\r\n                        {dede:channel type='son' noself='yes'}\r\n                        <li><a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a></li>\r\n                        {/dede:channel}\r\n                    </ul>\r\n                </div>\r\n            </li>\r\n            ",252,777);
$z[0][4]=array();
$z[0][4]['row']="10";
$z[0][4]['typeid']="top";

?>